name: Bug - Google Maps URL
description: File a bug report that a Google Maps URL doesn't work.
labels: ["bug"]
body:
  - type: input
    id: url
    attributes:
      label: Google Maps URL
      placeholder: |
          https://www.google.com/maps/place/Berlin,+Germany/@52.5067296,13.2599309,11z/data=abcdefg
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behaviour
      value: |
          The app shows 'Failed to create geo URL'.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the app are you running?
      placeholder: |
          Example: 1.2.0
    validations:
      required: true
  - type: input
    id: android
    attributes:
      label: Android
      description: What version of Android are you running?
      placeholder: "15"
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Anything else?
      description: |
          Do you have a hunch why the URL is not working? Are there other URLs that you suspect don't work for the same reason?

          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
