name: Feature request
description: "File a feature request."
labels: ["feature request"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What would you like to achieve using the app?
      placeholder: |
          Example: I would like to open links without needing to share them with the app first.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What should the app do to help you achieve your goal?
      placeholder: |
          Example: The app should use Android's 'unverified links' function.
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Anything else?
      description: |
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
